- params:
    git:
      repoName: flask-webgoat
      branches:
        - master
    scan:
      projects:
        - workingDirs:
            - action
          pipRequirementsFile: requirements.txt
